repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff linter
        entry: uv run ruff check --fix --exclude .pre-commit-cache
        language: system
        pass_filenames: false

      - id: ruff-format
        name: Ruff formatter
        entry: uv run ruff format --exclude .pre-commit-cache
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest -q
        language: system
        pass_filenames: false

      - id: mutmut
        name: Mutmut mutation tests
        entry: uv run mutmut run
        language: system
        stages: [manual]
        pass_filenames: false
        exclude: ^mutants/
